version: '3'
sevices:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: ECommerceDB
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server-utf8mb4_unicode_ci